version: 2
updates:
  - package-ecosystem: "pip"  # Poetry uses pip under the hood
    directory: "/"
    schedule:
      interval: "weekly"  # Check for updates weekly
    open-pull-requests-limit: 10  # Limit the number of open PRs
    labels:
      - "dependencies"
    commit-message:
      prefix: "chore"

  - package-ecosystem: "github-actions"  # Also update GitHub Actions
    directory: "/"
    schedule:
      interval: "weekly"
    labels:
      - "dependencies"
    commit-message:
      prefix: "ci"
