#!/usr/bin/env python3
"""
Generate the public ``.pyi`` stubs that ship in the wheel.

mypy's stubgen writes the structure (imports, signatures, overloads, re-exports). The passes in
`publicize` then drop private class members, so an IDE offers users only the public API, and repair
what stubgen gets wrong for this package's pydantic models.
"""

from __future__ import annotations

import argparse
import ast
import dataclasses
import importlib
import re
import subprocess
import sys
import tempfile
import types
import typing
from pathlib import Path

from logprise import logger
from mypy import stubgen
from pydantic.fields import FieldInfo
from pydantic_core import PydanticUndefined

# Version checks such as the StrEnum fallback resolve for the oldest supported Python, whichever runs this.
TARGET_VERSION = (3, 10)
HEADER = "# Generated by dev/generate_stubs.py from src/: edit the source and run ./restub instead.\n"
PYPROJECT = Path(__file__).resolve().parent.parent / "pyproject.toml"


def _is_private(name: str) -> bool:
    return name.startswith("_") and not (name.startswith("__") and name.endswith("__"))


def _bound_name(node: ast.stmt) -> str:
    """The name a statement defines, or "" when it defines none (or several)."""
    match node:
        case ast.FunctionDef(name=name) | ast.AsyncFunctionDef(name=name) | ast.ClassDef(name=name):
            return name
        case ast.AnnAssign(target=ast.Name(id=name)) | ast.Assign(targets=[ast.Name(id=name)]):
            return name
    return ""


def _imported_names(stub: ast.Module) -> set[str]:
    return {alias.asname or alias.name for node in stub.body if isinstance(node, (ast.Import, ast.ImportFrom)) for alias in node.names}


def _restore_source_imports(stub: ast.Module, source: ast.Module) -> None:
    """
    Add the source's imports the stub lacks, ``if TYPE_CHECKING:`` ones included; ruff then drops the unused ones.

    Stubgen leaves out an import that only a string (a TypeVar bound) or a decorator it doesn't know uses.
    """
    type_checking = [node.body for node in source.body if isinstance(node, ast.If) and ast.unparse(node.test) in ("TYPE_CHECKING", "typing.TYPE_CHECKING")]
    statements = [
        node
        for node in [*source.body, *(statement for block in type_checking for statement in block)]
        if isinstance(node, (ast.Import, ast.ImportFrom)) and getattr(node, "module", None) != "__future__"
    ]
    imported = _imported_names(stub)
    for statement in reversed(statements):
        if missing := [alias for alias in statement.names if (alias.asname or alias.name) not in imported]:
            statement.names = missing
            stub.body.insert(0, statement)


def _restore_class_decorators(stub: ast.Module, source: ast.Module) -> None:
    """Give every class its source decorators; stubgen keeps only those it knows, dropping pydantic's ``@dataclass`` for one."""
    decorators = {node.name: node.decorator_list for node in source.body if isinstance(node, ast.ClassDef)}
    for node in stub.body:
        if isinstance(node, ast.ClassDef) and node.name in decorators:
            node.decorator_list = decorators[node.name]


def _strip_private_members(stub: ast.Module, module: types.ModuleType) -> None:
    """Drop private attributes and methods from every class; dunders stay."""
    for node in stub.body:
        if not isinstance(node, ast.ClassDef):
            continue
        private = {name for member in node.body if _is_private(name := _bound_name(member))}
        runtime = getattr(module, node.name, None)
        if dataclasses.is_dataclass(runtime) and (hidden := private & {f.name for f in dataclasses.fields(runtime) if f.init}):
            raise ValueError(f"{node.name} takes private __init__ arguments {sorted(hidden)}, which a public stub can't hide")
        node.body = [member for member in node.body if _bound_name(member) not in private] or [ast.Expr(ast.Constant(...))]


def _type_source(annotation: object, module: types.ModuleType, imports: set[str]) -> str:
    """Source for a resolved type, recording the imports it needs."""
    if typing.get_origin(annotation) in (typing.Union, types.UnionType):
        return " | ".join(_type_source(arg, module, imports) for arg in typing.get_args(annotation))
    if not isinstance(annotation, type):
        raise TypeError(f"Can't render alias target {annotation!r}")
    if annotation.__module__ not in ("builtins", module.__name__):
        imports.add(f"from {annotation.__module__} import {annotation.__name__}")
    return annotation.__name__


def _resolve_annotated_aliases(stub: ast.Module, module: types.ModuleType) -> None:
    """Stubgen writes ``String = Annotated[str, ...]`` as ``String: Incomplete``; spell out the type it stands for."""
    imports: set[str] = set()
    for index, node in enumerate(stub.body):
        name = _bound_name(node)
        if isinstance(node, ast.AnnAssign) and node.value is None and typing.get_origin(alias := getattr(module, name, None)) is typing.Annotated:
            stub.body[index] = ast.parse(f"{name} = {_type_source(typing.get_args(alias)[0], module, imports)}").body[0]
    imported = _imported_names(stub)
    stub.body[:0] = [ast.parse(line).body[0] for line in sorted(imports) if line.rsplit(" ", 1)[-1] not in imported]


class _UnwrapAnnotated(ast.NodeTransformer):
    """``Annotated[X, ...]`` means ``X`` to a type checker; the metadata (stubgen writes it as None) is noise."""

    def visit_Subscript(self, node: ast.Subscript) -> ast.expr:  # pylint: disable=invalid-name  # the name NodeTransformer dispatches on
        self.generic_visit(node)
        if isinstance(node.value, ast.Name) and node.value.id == "Annotated" and isinstance(node.slice, ast.Tuple):
            return node.slice.elts[0]
        return node


def _stub_default(field_: dataclasses.Field) -> ast.expr | None:
    """A simple default as its literal, any other default as ``...``, and no default as None."""
    pydantic_field = field_.default if isinstance(field_.default, FieldInfo) else None  # pydantic keeps `Field(...)` as the default
    default = pydantic_field.default if pydantic_field else field_.default
    if default is not dataclasses.MISSING and default is not PydanticUndefined:
        return ast.Constant(default if type(default) in (str, int, float, bool, type(None)) else ...)  # an enum member's repr is no literal
    has_factory = field_.default_factory is not dataclasses.MISSING or (pydantic_field and pydantic_field.default_factory)
    return ast.Constant(...) if has_factory else None


def _declares_kw_only(node: ast.ClassDef) -> bool:
    """Whether the class's ``@dataclass(...)`` says ``kw_only=True``; the stub keeps that decorator as written."""
    return any(
        isinstance(decorator, ast.Call)
        and any(keyword.arg == "kw_only" and isinstance(keyword.value, ast.Constant) and keyword.value.value is True for keyword in decorator.keywords)
        for decorator in node.decorator_list
    )


def _settle_fields(node: ast.ClassDef, fields: tuple[dataclasses.Field, ...]) -> bool:
    """Set each field's value from the runtime field; True when one became ``field(init=False)``."""
    by_name = {field_.name: field_ for field_ in fields}
    members = [(member, field_) for member in node.body if isinstance(member, ast.AnnAssign) and (field_ := by_name.get(_bound_name(member)))]
    if not _declares_kw_only(node) and (keyword_only := [field_.name for _, field_ in members if field_.kw_only is True]):
        raise ValueError(f"{node.name} has keyword-only fields {keyword_only}; the stub only expresses a class-wide @dataclass(kw_only=True)")
    for member, field_ in members:
        member.value = _stub_default(field_) if field_.init else ast.parse("field(init=False)", mode="eval").body
    return any(not field_.init for _, field_ in members)


def _settle_dataclass_fields(stub: ast.Module, module: types.ModuleType) -> None:
    """A field's value shapes the synthesized ``__init__``; take it from the runtime field, as stubgen drops or garbles some."""
    uses_field = False
    for node in stub.body:
        if isinstance(node, ast.ClassDef) and isinstance(runtime := getattr(module, node.name, None), type) and dataclasses.is_dataclass(runtime):
            uses_field |= _settle_fields(node, dataclasses.fields(runtime))
    if uses_field and "field" not in _imported_names(stub):
        stub.body.insert(0, ast.ImportFrom("dataclasses", [ast.alias("field")], 0))


def _drop_unreferenced_privates(stub: ast.Module) -> None:
    """A private module-level name stays only while the rest of the stub refers to it (a TypeVar, a private base class)."""
    while True:
        sources = {id(node): ast.unparse(node) for node in stub.body}
        unused = [
            node
            for node in stub.body
            if _is_private(name := _bound_name(node)) and not any(re.search(rf"\b{name}\b", source) for key, source in sources.items() if key != id(node))
        ]
        if not unused:
            return
        stub.body = [node for node in stub.body if node not in unused]


def publicize(stub_source: str, module: types.ModuleType) -> str:
    """Rewrite one stubgen stub into the stub users see."""
    stub = ast.parse(stub_source)
    source = ast.parse(Path(typing.cast("str", module.__file__)).read_bytes())
    _restore_source_imports(stub, source)
    _restore_class_decorators(stub, source)
    _strip_private_members(stub, module)
    _resolve_annotated_aliases(stub, module)
    stub = _UnwrapAnnotated().visit(stub)
    _settle_dataclass_fields(stub, module)
    _drop_unreferenced_privates(stub)
    return HEADER + ast.unparse(ast.fix_missing_locations(stub)) + "\n"


def _run_stubgen(package_dir: Path, output_dir: Path) -> list[Path]:
    """Stubgen's own CLI path, with the target version pinned (its command line has no flag for that)."""
    options = stubgen.parse_options(["--no-import", "--include-private", "--quiet", "-o", str(output_dir), str(package_dir)])
    options.pyversion = TARGET_VERSION
    stubgen.generate_stubs(options)
    return sorted((output_dir / package_dir.name).glob("*.pyi"))


def _reformat(stub_dir: Path) -> None:
    # The project's settings wherever the stubs land (ruff's defaults rewrite `field(init=False)` in a stub).
    # isort's split-on-trailing-comma is off here only, so a single-name import collapses to one line.
    config = ["--config", str(PYPROJECT)]
    subprocess.run(
        ["ruff", "check", "--fix", "--unsafe-fixes", "--quiet", *config, "--config", "lint.isort.split-on-trailing-comma=false", str(stub_dir)], check=True
    )
    subprocess.run(["ruff", "format", "--quiet", *config, str(stub_dir)], check=True)


def sync_stubs(package_dir: Path, stub_dir: Path) -> None:
    """Regenerate ``stub_dir`` from ``package_dir``, pruning stubs whose module is gone."""
    package_dir, stub_dir = package_dir.resolve(), stub_dir.resolve()
    if str(package_dir.parent) not in sys.path:
        sys.path.insert(0, str(package_dir.parent))

    stub_dir.mkdir(parents=True, exist_ok=True)
    with tempfile.TemporaryDirectory() as tmp:
        generated = _run_stubgen(package_dir, Path(tmp))
        for orphan in sorted(set(stub_dir.glob("*.pyi")) - {stub_dir / stub.name for stub in generated}):
            orphan.unlink()
            logger.info(f"Pruned orphaned stub {orphan}")
        for stub in generated:
            module_name = package_dir.name if stub.stem == "__init__" else f"{package_dir.name}.{stub.stem}"
            (stub_dir / stub.name).write_text(publicize(stub.read_text(), importlib.import_module(module_name)))
    _reformat(stub_dir)


def main() -> None:
    parser = argparse.ArgumentParser(description="Regenerate the public stubs of a package")
    parser.add_argument("package_dir", type=Path, help="Package to generate stubs for, e.g. src/smartschool")
    parser.add_argument("stub_dir", type=Path, help="Where the stubs go, e.g. stubs/smartschool")
    args = parser.parse_args()
    sync_stubs(args.package_dir, args.stub_dir)


if __name__ == "__main__":
    main()
