# Generated by dev/generate_stubs.py from src/: edit the source and run ./restub instead.
from ._agenda import AgendaLesson as AgendaLesson
from ._agenda import AgendaPoster as AgendaPoster
from ._agenda import SmartschoolHours as SmartschoolHours
from ._agenda import SmartschoolLessons as SmartschoolLessons
from ._agenda import SmartschoolMomentInfos as SmartschoolMomentInfos
from ._common import IsSaved as IsSaved
from ._common import as_float as as_float
from ._common import bs4_html as bs4_html
from ._common import convert_to_date as convert_to_date
from ._common import convert_to_datetime as convert_to_datetime
from ._common import create_filesystem_safe_filename as create_filesystem_safe_filename
from ._common import create_filesystem_safe_path as create_filesystem_safe_path
from ._common import fill_form as fill_form
from ._common import get_all_values_from_form as get_all_values_from_form
from ._common import natural_sort as natural_sort
from ._common import parse_mime_type as parse_mime_type
from ._common import parse_size as parse_size
from ._common import save as save
from ._common import send_email as send_email
from ._common import xml_to_dict as xml_to_dict
from ._courses import CourseCondensed as CourseCondensed
from ._courses import CourseList as CourseList
from ._courses import Courses as Courses
from ._courses import DocumentOrFolderItem as DocumentOrFolderItem
from ._courses import FileItem as FileItem
from ._courses import FolderItem as FolderItem
from ._courses import InternetShortcut as InternetShortcut
from ._courses import TopNavCourses as TopNavCourses
from ._credentials import AppCredentials as AppCredentials
from ._credentials import Credentials as Credentials
from ._credentials import EnvCredentials as EnvCredentials
from ._credentials import KeyringCredentials as KeyringCredentials
from ._credentials import PathCredentials as PathCredentials
from ._exceptions import SmartSchoolAttachmentUploadError as SmartSchoolAttachmentUploadError
from ._exceptions import SmartSchoolAuthenticationError as SmartSchoolAuthenticationError
from ._exceptions import SmartSchoolCoAccountsUnavailableError as SmartSchoolCoAccountsUnavailableError
from ._exceptions import SmartSchoolDownloadError as SmartSchoolDownloadError
from ._exceptions import SmartSchoolException as SmartSchoolException
from ._exceptions import SmartSchoolJsonError as SmartSchoolJsonError
from ._exceptions import SmartSchoolParsingError as SmartSchoolParsingError
from ._future_tasks import FutureTasks as FutureTasks
from ._intradesk import Intradesk as Intradesk
from ._intradesk import IntradeskFile as IntradeskFile
from ._intradesk import IntradeskFolder as IntradeskFolder
from ._intradesk import IntradeskItem as IntradeskItem
from ._message_composer import MessageComposerForm as MessageComposerForm
from ._message_composer import RecipientType as RecipientType
from ._messages import AdjustMessageLabel as AdjustMessageLabel
from ._messages import Attachment as Attachment
from ._messages import Attachments as Attachments
from ._messages import BoxType as BoxType
from ._messages import MarkMessageUnread as MarkMessageUnread
from ._messages import Message as Message
from ._messages import MessageHeaders as MessageHeaders
from ._messages import MessageLabel as MessageLabel
from ._messages import MessageMoveToArchive as MessageMoveToArchive
from ._messages import MessageMoveToTrash as MessageMoveToTrash
from ._messages import SortField as SortField
from ._messages import SortOrder as SortOrder
from ._mydocs import MyDocs as MyDocs
from ._mydocs import MyDocsFile as MyDocsFile
from ._mydocs import MyDocsFolder as MyDocsFolder
from ._mydocs import MyDocsItem as MyDocsItem
from ._objects import AgendaHour as AgendaHour
from ._objects import AgendaMomentInfo as AgendaMomentInfo
from ._objects import AgendaMomentInfoAssignment as AgendaMomentInfoAssignment
from ._objects import ApplicableAssignmentType as ApplicableAssignmentType
from ._objects import Component as Component
from ._objects import Course as Course
from ._objects import CourseGraphic as CourseGraphic
from ._objects import DateRange as DateRange
from ._objects import Feedback as Feedback
from ._objects import FeedbackFull as FeedbackFull
from ._objects import FullMessage as FullMessage
from ._objects import FutureTaskOneCourse as FutureTaskOneCourse
from ._objects import FutureTaskOneDay as FutureTaskOneDay
from ._objects import FutureTaskOneItem as FutureTaskOneItem
from ._objects import FutureTaskOneTask as FutureTaskOneTask
from ._objects import GraphicColor as GraphicColor
from ._objects import GroupFilters as GroupFilters
from ._objects import IconGraphic as IconGraphic
from ._objects import MessageChanged as MessageChanged
from ._objects import MessageDeletionStatus as MessageDeletionStatus
from ._objects import MessageSearchGroup as MessageSearchGroup
from ._objects import MessageSearchUser as MessageSearchUser
from ._objects import PercentageGraphic as PercentageGraphic
from ._objects import Period as Period
from ._objects import PersonDescription as PersonDescription
from ._objects import PlannedElement as PlannedElement
from ._objects import PlannedElementAssignmentType as PlannedElementAssignmentType
from ._objects import PlannedElementCourse as PlannedElementCourse
from ._objects import PlannedElementCourseCluster as PlannedElementCourseCluster
from ._objects import PlannedElementJoinIds as PlannedElementJoinIds
from ._objects import PlannedElementLocation as PlannedElementLocation
from ._objects import PlannedElementOrganisers as PlannedElementOrganisers
from ._objects import PlannedElementParticipants as PlannedElementParticipants
from ._objects import PlannedElementPeriod as PlannedElementPeriod
from ._objects import ResultDetails as ResultDetails
from ._objects import ResultType as ResultType
from ._objects import SchoolClass as SchoolClass
from ._objects import ShortMessage as ShortMessage
from ._objects import SkoreWorkYear as SkoreWorkYear
from ._objects import Student as Student
from ._objects import StudentSupportLink as StudentSupportLink
from ._objects import Teacher as Teacher
from ._objects import TextGraphic as TextGraphic
from ._objects import UserCapabilities as UserCapabilities
from ._objects import UserSeeProperties as UserSeeProperties
from ._periods import Periods as Periods
from ._planner import ApplicableAssignmentTypes as ApplicableAssignmentTypes
from ._planner import PlannedElements as PlannedElements
from ._reports import Report as Report
from ._reports import Reports as Reports
from ._results import Result as Result
from ._results import Results as Results
from ._session import Smartschool as Smartschool
from ._student_support import StudentSupportLinks as StudentSupportLinks

__all__ = [
    "AdjustMessageLabel",
    "AgendaHour",
    "AgendaLesson",
    "AgendaMomentInfo",
    "AgendaMomentInfoAssignment",
    "AgendaPoster",
    "AppCredentials",
    "ApplicableAssignmentType",
    "ApplicableAssignmentTypes",
    "Attachment",
    "Attachments",
    "BoxType",
    "Component",
    "Course",
    "CourseCondensed",
    "CourseGraphic",
    "CourseList",
    "Courses",
    "Credentials",
    "DateRange",
    "DocumentOrFolderItem",
    "EnvCredentials",
    "Feedback",
    "FeedbackFull",
    "FileItem",
    "FolderItem",
    "FullMessage",
    "FutureTaskOneCourse",
    "FutureTaskOneDay",
    "FutureTaskOneItem",
    "FutureTaskOneTask",
    "FutureTasks",
    "GraphicColor",
    "GroupFilters",
    "IconGraphic",
    "InternetShortcut",
    "Intradesk",
    "IntradeskFile",
    "IntradeskFolder",
    "IntradeskItem",
    "IsSaved",
    "KeyringCredentials",
    "MarkMessageUnread",
    "Message",
    "MessageChanged",
    "MessageComposerForm",
    "MessageDeletionStatus",
    "MessageHeaders",
    "MessageLabel",
    "MessageMoveToArchive",
    "MessageMoveToTrash",
    "MessageSearchGroup",
    "MessageSearchUser",
    "MyDocs",
    "MyDocsFile",
    "MyDocsFolder",
    "MyDocsItem",
    "PathCredentials",
    "PercentageGraphic",
    "Period",
    "Periods",
    "PersonDescription",
    "PlannedElement",
    "PlannedElementAssignmentType",
    "PlannedElementCourse",
    "PlannedElementCourseCluster",
    "PlannedElementJoinIds",
    "PlannedElementLocation",
    "PlannedElementOrganisers",
    "PlannedElementParticipants",
    "PlannedElementPeriod",
    "PlannedElements",
    "RecipientType",
    "Report",
    "Reports",
    "Result",
    "ResultDetails",
    "ResultType",
    "Results",
    "SchoolClass",
    "ShortMessage",
    "SkoreWorkYear",
    "SmartSchoolAttachmentUploadError",
    "SmartSchoolAuthenticationError",
    "SmartSchoolCoAccountsUnavailableError",
    "SmartSchoolDownloadError",
    "SmartSchoolException",
    "SmartSchoolJsonError",
    "SmartSchoolParsingError",
    "Smartschool",
    "SmartschoolHours",
    "SmartschoolLessons",
    "SmartschoolMomentInfos",
    "SortField",
    "SortOrder",
    "Student",
    "StudentSupportLink",
    "StudentSupportLinks",
    "Teacher",
    "TextGraphic",
    "TopNavCourses",
    "UserCapabilities",
    "UserSeeProperties",
    "as_float",
    "bs4_html",
    "convert_to_date",
    "convert_to_datetime",
    "create_filesystem_safe_filename",
    "create_filesystem_safe_path",
    "fill_form",
    "get_all_values_from_form",
    "natural_sort",
    "parse_mime_type",
    "parse_size",
    "save",
    "send_email",
    "xml_to_dict",
]
