# Generated by dev/generate_stubs.py from src/: edit the source and run ./restub instead.
import abc
from abc import ABC
from dataclasses import dataclass

from . import _objects as objects
from ._session import SessionMixin, Smartschool
from ._xml_interface import SmartschoolXmlWeeklyCache

__all__ = ["AgendaLesson", "AgendaPoster", "SmartschoolHours", "SmartschoolLessons", "SmartschoolMomentInfos"]

@dataclass
class AgendaPoster(SmartschoolXmlWeeklyCache, ABC, metaclass=abc.ABCMeta): ...

@dataclass
class AgendaLesson(SessionMixin, objects.AgendaLesson):
    @property
    def hour_details(self) -> objects.AgendaHour: ...

@dataclass
class SmartschoolLessons(AgendaPoster): ...

class SmartschoolHours(AgendaPoster):
    def search_by_hour_id(self, hour_id: str): ...

class SmartschoolMomentInfos(AgendaPoster):
    def __init__(self, session: Smartschool, moment_id: str) -> None: ...
