# Generated by dev/generate_stubs.py from src/: edit the source and run ./restub instead.
import abc
from abc import ABC, abstractmethod
from collections.abc import Callable
from datetime import date, datetime
from enum import Enum
from pathlib import Path
from typing import Any, Literal, overload

from bs4 import BeautifulSoup
from requests import Response

from ._objects import String
from ._session import Smartschool

__all__ = [
    "IsSaved",
    "as_float",
    "bs4_html",
    "convert_to_date",
    "convert_to_datetime",
    "create_filesystem_safe_filename",
    "create_filesystem_safe_path",
    "fill_form",
    "get_all_values_from_form",
    "natural_sort",
    "parse_mime_type",
    "parse_size",
    "parse_smsc_vars",
    "save",
    "send_email",
    "xml_to_dict",
]

class IsSaved(Enum):
    NEW = ...
    SAME = ...

def save(
    session: Smartschool,
    type_: Literal["agenda", "punten", "todo"],
    course_name: str,
    id_: str,
    data: dict | str | Any,
    is_eq: Callable = ...,
    extension: str = "json",
) -> IsSaved | dict | str | Any: ...
def send_email(subject: str, text: str, email_to: list[str] | str, email_from: str): ...
def bs4_html(html: str | bytes | Response) -> BeautifulSoup: ...
def parse_smsc_vars(text: str) -> dict: ...
def get_all_values_from_form(html: BeautifulSoup, form_selector: str): ...
def fill_form(response: str | bytes | Response, form_selector, values: dict[str, str]) -> dict[str, str]: ...
def as_float(txt: str) -> float: ...
def xml_to_dict(element, *, depth: int = 0): ...
def convert_to_datetime(x: str | String | date | datetime | None) -> datetime: ...
def convert_to_date(x: str | String | date | datetime | None) -> date: ...
def parse_size(size_str: str | float | None) -> float | None: ...
def parse_mime_type(file_type_string: str) -> str: ...
def create_filesystem_safe_path(path: Path | str) -> Path: ...
def create_filesystem_safe_filename(filename: str) -> str: ...

class DownloadableFile(ABC, metaclass=abc.ABCMeta):
    @overload
    def download(self, to_file: Path | str, *, overwrite: bool = False) -> Path: ...
    @overload
    def download(self) -> bytes: ...
    def download_to_dir(self, target_directory: Path, *, overwrite: bool = False) -> Path: ...
    @property
    @abstractmethod
    def filename(self) -> str: ...

def natural_sort(text: str, *, case_insensitive: bool = True) -> tuple[str | int, ...]: ...
