# Generated by dev/generate_stubs.py from src/: edit the source and run ./restub instead.
from collections.abc import Iterator
from dataclasses import dataclass
from datetime import datetime
from functools import cached_property
from typing import TypeAlias

from . import _objects as objects
from ._common import DownloadableFile
from ._session import SessionMixin

__all__ = ["CourseCondensed", "CourseList", "Courses", "DocumentOrFolderItem", "FileItem", "FolderItem", "InternetShortcut", "TopNavCourses"]

@dataclass
class CourseCondensed(objects.CourseCondensed, SessionMixin):
    def __str__(self) -> str: ...
    @property
    def items(self) -> list[DocumentOrFolderItem]: ...

@dataclass
class TopNavCourses(SessionMixin):
    def __iter__(self) -> Iterator[CourseCondensed]: ...

@dataclass
class Courses(SessionMixin):
    def __iter__(self) -> Iterator[objects.Course]: ...

@dataclass
class CourseList(SessionMixin):
    def __iter__(self) -> Iterator[objects.PlannedElementCourse]: ...

@dataclass
class FileItem(DownloadableFile, SessionMixin):
    parent: FolderItem
    id: int
    name: str
    mime_type: str
    size_kb: float | str | None
    last_modified: datetime | str
    download_url: str | None = None
    view_url: str | None = None

    def __post_init__(self) -> None: ...
    @cached_property
    def filename(self) -> str: ...

@dataclass
class InternetShortcut(FileItem):
    link: str = ""

    def __post_init__(self) -> None: ...
    @cached_property
    def filename(self) -> str: ...

@dataclass
class FolderItem(SessionMixin):
    parent: FolderItem | None
    course: CourseCondensed
    name: str
    browse_url: str | None = None

    def __post_init__(self) -> None: ...
    @cached_property
    def items(self) -> list[DocumentOrFolderItem]: ...

DocumentOrFolderItem: TypeAlias = FileItem | FolderItem | InternetShortcut
