# Generated by dev/generate_stubs.py from src/: edit the source and run ./restub instead.
from dataclasses import dataclass, field
from pathlib import Path
from typing import ClassVar

__all__ = ["AppCredentials", "Credentials", "EnvCredentials", "KeyringCredentials", "PathCredentials"]

class Credentials:
    username: str
    password: str
    mfa: str
    main_url: str
    other_info: dict | None

    def validate(self) -> None: ...
    def as_dict(self) -> dict[str, str | dict]: ...

@dataclass(frozen=True)
class PathCredentials(Credentials):
    CREDENTIALS_FILENAME: ClassVar[str] = ...
    filename: str | Path = ""
    username: str = field(init=False)
    password: str = field(init=False)
    main_url: str = field(init=False)
    mfa: str = field(init=False)
    other_info: dict | None = field(init=False)

    def __post_init__(self) -> None: ...

@dataclass(frozen=True)
class EnvCredentials(Credentials):
    def __post_init__(self) -> None: ...

@dataclass(frozen=True, kw_only=True)
class KeyringCredentials(Credentials):
    username: str = ""
    main_url: str = ""
    mfa: str = ""
    service: str = "smartschool"
    password: str = field(init=False)

    def __post_init__(self) -> None: ...

@dataclass(frozen=True)
class AppCredentials(Credentials):
    username: str = ""
    password: str = ""
    main_url: str = ""
    mfa: str = ""
