# Generated by dev/generate_stubs.py from src/: edit the source and run ./restub instead.
import abc
from collections.abc import Callable as Callable
from dataclasses import dataclass
from pathlib import Path

from requests.models import PreparedRequest as PreparedRequest
from requests.models import Response as Response

@dataclass
class DevTracingMixin(abc.ABC, metaclass=abc.ABCMeta):
    @property
    def dev_tracing(self) -> bool: ...
    @property
    @abc.abstractmethod
    def cache_path(self) -> Path: ...
