# Generated by dev/generate_stubs.py from src/: edit the source and run ./restub instead.
from dataclasses import dataclass

from requests import Response

__all__ = [
    "SmartSchoolAttachmentUploadError",
    "SmartSchoolAuthenticationError",
    "SmartSchoolCoAccountsUnavailableError",
    "SmartSchoolDownloadError",
    "SmartSchoolException",
    "SmartSchoolJsonError",
    "SmartSchoolParsingError",
]

@dataclass
class SmartSchoolException(Exception):
    message: str

    def __str__(self) -> str: ...

class SmartSchoolAuthenticationError(SmartSchoolException): ...
class SmartSchoolParsingError(SmartSchoolException): ...
class SmartSchoolAttachmentUploadError(SmartSchoolException): ...

@dataclass
class SmartSchoolCoAccountsUnavailableError(SmartSchoolException):
    message: str = "This account cannot message co-accounts"

@dataclass
class SmartSchoolDownloadError(SmartSchoolException):
    response: Response
    status_code: int = ...

    def __post_init__(self) -> None: ...

@dataclass
class SmartSchoolJsonError(SmartSchoolDownloadError): ...
