# Generated by dev/generate_stubs.py from src/: edit the source and run ./restub instead.
from collections.abc import Iterator
from dataclasses import dataclass

from ._objects import FutureTaskOneDay
from ._session import SessionMixin

__all__ = ["FutureTasks"]

@dataclass
class FutureTasks(SessionMixin):
    def __iter__(self) -> Iterator[FutureTaskOneDay]: ...
