# Generated by dev/generate_stubs.py from src/: edit the source and run ./restub instead.
from collections.abc import Iterator
from dataclasses import dataclass
from functools import cached_property
from typing import TypeAlias

from ._common import DownloadableFile
from ._session import SessionMixin

__all__ = ["Intradesk", "IntradeskFile", "IntradeskFolder", "IntradeskItem"]

@dataclass
class IntradeskFile(DownloadableFile, SessionMixin):
    parent: IntradeskFolder
    id: str = ""
    name: str = ""

    @cached_property
    def filename(self) -> str: ...

@dataclass
class IntradeskFolder(SessionMixin):
    parent: IntradeskFolder | None = None
    id: str = ""
    name: str = ""

    @cached_property
    def items(self) -> list[IntradeskItem]: ...
    def __iter__(self) -> Iterator[IntradeskItem]: ...

@dataclass
class Intradesk(IntradeskFolder):
    name: str = "intradesk"

IntradeskItem: TypeAlias = IntradeskFile | IntradeskFolder
