# Generated by dev/generate_stubs.py from src/: edit the source and run ./restub instead.
import abc
from abc import ABC
from collections.abc import Iterator
from dataclasses import dataclass
from enum import Enum

from _typeshed import Incomplete

from . import _objects as objects
from ._session import SessionMixin, Smartschool
from ._xml_interface import SmartschoolXML, SmartschoolXmlNoCache, _ItemT_co

__all__ = [
    "AdjustMessageLabel",
    "Attachment",
    "Attachments",
    "BoxType",
    "MarkMessageUnread",
    "Message",
    "MessageHeaders",
    "MessageLabel",
    "MessageMoveToArchive",
    "MessageMoveToTrash",
    "SortField",
    "SortOrder",
]

class SortField(Enum):
    DATE = "date"
    FROM = "from"
    READ_UNREAD = "status"
    ATTACHMENT = "attachment"
    FLAG = "label"

class SortOrder(Enum):
    ASC = "asc"
    DESC = "desc"

class BoxType(Enum):
    INBOX = "inbox"
    DRAFT = "draft"
    SCHEDULED = "scheduled"
    SENT = "outbox"
    TRASH = "trash"

class MessageLabel(Enum):
    NO_FLAG = 0
    GREEN_FLAG = 1
    YELLOW_FLAG = 2
    RED_FLAG = 3
    BLUE_FLAG = 4

class _MessagesPoster: ...

@dataclass
class MessageHeaders(_MessagesPoster, SmartschoolXmlNoCache[objects.ShortMessage]):
    box_type: BoxType = ...
    sort_by: SortField = ...
    sort_order: SortOrder = ...
    already_seen_message_ids: list[int] | None = ...

class _FetchOneMessage(_MessagesPoster, SmartschoolXML[_ItemT_co], ABC, metaclass=abc.ABCMeta):
    msg_id: Incomplete
    box_type: Incomplete

    def __init__(self, session: Smartschool, msg_id: int, box_type: BoxType = ...) -> None: ...

class Message(_FetchOneMessage[objects.FullMessage]): ...

@dataclass
class Attachment(SessionMixin, objects.Attachment):
    def download(self) -> bytes: ...

class Attachments(_FetchOneMessage[Attachment]): ...
class MarkMessageUnread(_FetchOneMessage[objects.MessageChanged]): ...

class AdjustMessageLabel(_FetchOneMessage[objects.MessageChanged]):
    label: Incomplete

    def __init__(self, session: Smartschool, msg_id: int, box_type: BoxType = ..., label: MessageLabel = ...) -> None: ...

@dataclass
class MessageMoveToArchive(SessionMixin):
    msg_ids = ...

    def __init__(self, session: Smartschool, msg_id: int | list[int]) -> None: ...
    def get(self) -> objects.MessageChanged: ...
    def __iter__(self) -> Iterator[objects.MessageChanged]: ...

class MessageMoveToTrash(_MessagesPoster, SmartschoolXmlNoCache[objects.MessageDeletionStatus]):
    msg_id: Incomplete

    def __init__(self, session: Smartschool, msg_id: int) -> None: ...
