# Generated by dev/generate_stubs.py from src/: edit the source and run ./restub instead.
from collections.abc import Iterator
from dataclasses import dataclass
from functools import cached_property
from pathlib import Path
from typing import TypeAlias, TypeVar

from ._common import DownloadableFile
from ._session import SessionMixin, Smartschool

__all__ = ["MyDocs", "MyDocsFile", "MyDocsFolder", "MyDocsItem"]
_ItemT = TypeVar("_ItemT", bound="_MyDocsItem")

class _MyDocsItem:
    session: Smartschool
    id: str
    name: str
    is_favourite: bool
    parent: MyDocsFolder | None

    def rename(self, new_name: str) -> _ItemT: ...
    def move(self, target: MyDocsFolder) -> _ItemT: ...
    def copy(self, target: MyDocsFolder) -> MyDocsItem: ...
    def trash(self) -> None: ...
    def restore(self, into: MyDocsFolder | None = None) -> _ItemT: ...
    def mark_favourite(self) -> _ItemT: ...
    def unmark_favourite(self) -> _ItemT: ...

@dataclass
class MyDocsFile(_MyDocsItem, DownloadableFile, SessionMixin):
    parent: MyDocsFolder
    id: str = ""
    name: str = ""
    revision_id: str = ""
    size: int = 0
    is_favourite: bool = False

    @cached_property
    def filename(self) -> str: ...
    def is_dir(self) -> bool: ...
    def is_file(self) -> bool: ...
    def delete(self) -> None: ...

@dataclass
class MyDocsFolder(_MyDocsItem, SessionMixin):
    parent: MyDocsFolder | None = None
    id: str = ""
    name: str = ""
    color: str = ""
    is_favourite: bool = False

    def is_dir(self) -> bool: ...
    def is_file(self) -> bool: ...
    @cached_property
    def items(self) -> list[MyDocsItem]: ...
    def refresh(self) -> None: ...
    def __iter__(self) -> Iterator[MyDocsItem]: ...
    def create_folder(self, name: str, *, color: str = "blue") -> MyDocsFolder: ...
    def upload(self, file_path: str | Path) -> MyDocsFile: ...
    def delete(self) -> None: ...

@dataclass
class MyDocs(MyDocsFolder):
    name: str = "mydocs"

MyDocsItem: TypeAlias = MyDocsFile | MyDocsFolder
