# Generated by dev/generate_stubs.py from src/: edit the source and run ./restub instead.
from datetime import date, datetime
from enum import Enum
from functools import cached_property as cached_property
from typing import Literal

from pydantic.dataclasses import dataclass

from ._common import as_float as as_float
from ._common import convert_to_date as convert_to_date
from ._common import convert_to_datetime as convert_to_datetime

class StrEnum(str, Enum):
    __str__ = ...

String = str
UUID = str
Url = String
Date = date
DateTime = datetime

class GraphicColor(StrEnum):
    GREEN = "green"
    RED = "red"
    OLIVE = "olive"
    YELLOW = "yellow"
    STEEL = "steel"
    GRASS = "grass"

class ResultType(StrEnum):
    NORMAL = "normal"
    PROJECT_WITH_RUBRICS = "project-with-rubrics"

@dataclass
class CourseGraphic:
    type: Literal["icon", "image"]
    value: String

@dataclass
class PercentageGraphic:
    type: Literal["percentage"]
    color: GraphicColor
    value: int
    description: String

    @cached_property
    def achieved_points(self) -> float: ...
    @cached_property
    def total_points(self) -> float: ...
    @property
    def percentage(self) -> float: ...

@dataclass
class TextGraphic:
    type: Literal["text"]
    color: GraphicColor
    value: String
    description: String

@dataclass
class IconGraphic:
    type: Literal["icon"]
    color: String | None = None
    value: String | None = None
    description: String | None = None

ResultGraphic = PercentageGraphic | TextGraphic | IconGraphic

@dataclass
class PersonDescription:
    starting_with_first_name: String = ""
    starting_with_last_name: String = ""

@dataclass
class _User:
    id: String
    picture_hash: String
    picture_url: Url
    description: PersonDescription
    name: PersonDescription
    sort: String
    deleted: bool = False

@dataclass
class _Group:
    identifier: String
    id: String
    platform_id: int
    name: String
    type: String
    icon: String
    sort: String

@dataclass
class DateRange:
    start: DateTime
    end: DateTime

@dataclass
class SkoreWorkYear:
    id: int
    date_range: DateRange

@dataclass
class SchoolClass:
    identifier: String
    id: int
    platform_id: int
    name: String
    type: String
    icon: String

@dataclass
class Period:
    id: int
    name: String
    icon: String
    skore_work_year: SkoreWorkYear
    is_active: bool
    class_: SchoolClass

@dataclass
class Component:
    id: int
    name: String
    abbreviation: String

@dataclass
class Teacher(_User): ...

@dataclass
class Student(_User): ...

@dataclass
class Course:
    id: int
    name: String
    graphic: CourseGraphic
    teachers: list[Teacher]
    skore_class_id: int
    parent_course_id: int | None
    skore_work_year: SkoreWorkYear
    class_: SchoolClass

    def __str__(self) -> str: ...

@dataclass
class Feedback:
    text: String
    user: Teacher

@dataclass
class FeedbackFull:
    attachments: list[String]
    changed_at: DateTime
    created_at: DateTime
    evaluation_id: String
    id: String
    student: Student
    teacher: Teacher
    text: String

@dataclass
class Result:
    identifier: String
    type: ResultType
    name: String
    graphic: ResultGraphic
    date: DateTime
    gradebook_owner: Teacher
    component: Component | None
    courses: list[Course]
    period: Period
    feedback: list[Feedback]
    feedbacks: list[FeedbackFull]
    availability_date: DateTime
    is_published: bool
    does_count: bool
    deleted: bool = False
    details: ResultDetails | None = None

@dataclass
class ResultDetails:
    central_tendencies: list[String]
    teachers: list[Teacher]
    date_changed: DateTime
    user_changed: Teacher
    class_: SchoolClass

@dataclass
class CourseCondensed:
    name: String
    teacher: String
    url: Url
    id: int | None = None
    platform_id: int | None = None
    descr: String = ""
    icon: String = ""

@dataclass
class FutureTaskOneTask:
    label: String
    description: String
    icon: String
    warning: bool
    click_handle: String
    activity_id: int
    date_id: String
    assignment_id: String
    end_moment_ts: String | None
    start_moment_id: String
    end_moment_id: String
    lesson_id: String
    type: String
    class_id: String
    course: String
    date: Date
    hour_id: String

@dataclass
class FutureTaskOneItem:
    tasks: list[FutureTaskOneTask]
    materials: list[String]

@dataclass
class FutureTaskOneCourse:
    lesson_id: String
    hour_id: String
    class_id: String
    course_title: String
    items: FutureTaskOneItem

@dataclass
class FutureTaskOneDay:
    date: Date
    pretty_date: String
    courses: list[FutureTaskOneCourse]

@dataclass
class AgendaHour:
    hour_id: String
    start: String
    end: String
    title: String

@dataclass
class AgendaLesson:
    moment_id: String
    lesson_id: String
    hour_id: String
    date: Date
    subject: String | None
    course: String
    course_title: String
    classroom: String
    classroom_title: String
    teacher: String
    teacher_title: String
    klassen: String
    klassen_title: String
    class_ids: String
    both_start_status: String
    assignment_end_status: String
    test_deadline_status: String
    note_status: String
    note: String | None
    date_listview: String
    hour: String
    activity: String
    activity_id: String | None
    color: String
    hour_value: String
    components_hidden: object
    freeday_icon: String
    some_subjects_empty: String | None

@dataclass
class AgendaMomentInfoAssignment:
    start_assignment: String
    start: String
    end: String
    type: String
    description: String
    atdescription: String
    freedeadline: String
    warning: String
    assignment_info: String
    assignment_deadline: String

@dataclass
class AgendaMomentInfo:
    class_name: String
    subject: String
    materials: String | None
    moment_id: String
    assignments: list[AgendaMomentInfoAssignment]

@dataclass
class StudentSupportLink:
    id: String
    name: String
    description: String
    icon: String
    link: Url
    clean_link: String
    is_visible: bool

@dataclass
class ShortMessage:
    id: int
    from_image: Url
    subject: String
    date: DateTime
    status: int
    attachment: int
    unread: bool
    deleted: bool
    allowreply: bool
    allowreplyenabled: bool
    hasreply: bool
    has_forward: bool
    real_box: String
    send_date: DateTime | None
    from_: String
    colored_flag: int = 0

@dataclass
class FullMessage:
    id: int
    to: String | None
    subject: String
    date: DateTime
    body: String
    status: int
    attachment: int
    unread: bool
    receivers: list[String]
    ccreceivers: list[String]
    bccreceivers: list[String]
    sender_picture: String
    marked_in_lvs: None
    from_team: int
    total_nr_other_to_reciviers: int
    total_nr_other_cc_receivers: int
    total_nr_other_bcc_receivers: int
    can_reply: bool
    has_reply: bool
    has_forward: bool
    send_date: DateTime | None
    from_: String
    colored_flag: int = 0

@dataclass
class Attachment:
    file_id: int
    name: String
    mime: String
    size: String
    icon: String
    wopi_allowed: bool
    order: int

@dataclass
class MessageChanged:
    id: int
    new: int

@dataclass
class MessageDeletionStatus:
    msg_id: int
    box_type: String
    is_deleted: bool

@dataclass
class MessageSearchUser:
    user_id: int
    value: String
    ss_id: int
    user_lt: int = 0
    coaccountname: String | None = None
    classname: String | None = None
    schoolname: String | None = None
    picture: Url | None = None

@dataclass
class MessageSearchGroup:
    group_id: int
    value: String
    ss_id: int
    icon: String | None = None
    description: String | None = None

@dataclass
class PlannedElementPeriod:
    date_time_from: datetime
    date_time_to: datetime
    whole_day: bool
    deadline: bool

@dataclass
class PlannedElementOrganisers:
    users: list[_User]

@dataclass
class GroupFilters:
    filters: list
    additional_users: list[_User]

@dataclass
class PlannedElementParticipants:
    groups: list[_Group]
    users: list[_User]
    group_filters: GroupFilters

@dataclass
class UserSeeProperties:
    id: bool
    platform_id: bool
    period: bool
    organisers: bool
    planned_element_type: bool
    capabilities: bool
    name: bool = False
    participants: bool = False
    is_participant: bool = False
    courses: bool = False
    locations: bool = False

@dataclass
class UserCapabilities:
    can_user_trash: bool
    can_user_restore_from_trash: bool
    can_user_delete: bool
    can_user_edit: bool
    can_user_replace: bool
    can_user_reschedule: bool
    can_user_change_user_color: bool
    can_user_see_properties: UserSeeProperties
    can_user_edit_presence: bool = False
    can_user_change_user_view_metadata: bool = False
    can_user_change_organisers: bool = False
    can_user_change_participants: bool = False
    can_user_change_participant_group_filters: bool = False
    can_user_change_courses: bool = False
    can_user_change_locations: bool = False
    can_user_create_video_call: bool = False
    can_user_see_video_call: bool = False
    can_user_manage_video_call: bool = False

@dataclass
class PlannedElementCourseCluster:
    id: int
    name: String

@dataclass
class PlannedElementCourse:
    id: UUID
    platform_id: int
    name: String
    schedule_codes: list[String]
    icon: String
    course_cluster: PlannedElementCourseCluster | None
    is_visible: bool

@dataclass
class PlannedElementLocation:
    id: UUID
    platform_id: int
    platform_name: String
    number: String
    title: String
    icon: String
    type: String
    selectable: bool

@dataclass
class PlannedElementJoinIds:
    from_: String
    to: String

@dataclass
class PlannedElementAssignmentType:
    id: UUID
    name: String
    abbreviation: String
    is_visible: bool
    weight: int

@dataclass
class PlannedElement:
    id: UUID
    platform_id: int
    period: PlannedElementPeriod
    organisers: PlannedElementOrganisers
    planned_element_type: String
    capabilities: UserCapabilities
    sort: String
    unconfirmed: bool
    pinned: bool
    color: String
    join_ids: PlannedElementJoinIds
    name: String = ""
    participants: PlannedElementParticipants | None = None
    is_participant: bool = False
    courses: list[PlannedElementCourse] = ...
    locations: list[PlannedElementLocation] = ...
    assignment_type: PlannedElementAssignmentType | None = None
    resolved_status: String = ""
    online_session: String | None = None

@dataclass
class ApplicableAssignmentType:
    id: UUID
    platform_id: int
    name: String
    abbreviation: String
    is_visible: bool
    weight: float

@dataclass
class Report:
    id: int
    name: String
    icon: String
    date: DateTime
    download_url: Url
    class_: SchoolClass
    schoolyear_label: String
