# Generated by dev/generate_stubs.py from src/: edit the source and run ./restub instead.
from collections.abc import Iterator
from dataclasses import dataclass

from ._objects import Period
from ._session import SessionMixin

__all__ = ["Periods"]

@dataclass
class Periods(SessionMixin):
    def __iter__(self) -> Iterator[Period]: ...
