# Generated by dev/generate_stubs.py from src/: edit the source and run ./restub instead.
from collections.abc import Iterable, Iterator
from dataclasses import dataclass
from datetime import date

from ._objects import ApplicableAssignmentType, PlannedElement
from ._session import SessionMixin

__all__ = ["ApplicableAssignmentTypes", "PlannedElements"]

@dataclass
class ApplicableAssignmentTypes(SessionMixin, Iterable[ApplicableAssignmentType]):
    def __iter__(self) -> Iterator[ApplicableAssignmentType]: ...

@dataclass
class PlannedElements(SessionMixin, Iterable[PlannedElement]):
    from_date: date = ...
    till_date: date | None = None

    def __post_init__(self) -> None: ...
    def __iter__(self) -> Iterator[PlannedElement]: ...
