# Generated by dev/generate_stubs.py from src/: edit the source and run ./restub instead.
from collections.abc import Iterable, Iterator
from dataclasses import dataclass

from . import _objects as objects
from ._session import SessionMixin

__all__ = ["Report", "Reports"]

@dataclass
class Report(objects.Report, SessionMixin):
    def download(self) -> bytes: ...

@dataclass
class Reports(SessionMixin, Iterable[Report]):
    def __iter__(self) -> Iterator[Report]: ...
