# Generated by dev/generate_stubs.py from src/: edit the source and run ./restub instead.
from collections.abc import Iterable, Iterator
from dataclasses import dataclass

from ._objects import StudentSupportLink
from ._session import SessionMixin

__all__ = ["StudentSupportLinks"]

@dataclass
class StudentSupportLinks(SessionMixin, Iterable[StudentSupportLink]):
    def __iter__(self) -> Iterator[StudentSupportLink]: ...
