# Generated by dev/generate_stubs.py from src/: edit the source and run ./restub instead.
import abc
from abc import ABC
from collections.abc import Iterator
from dataclasses import dataclass
from datetime import date, datetime
from typing import TypeVar

from ._common import xml_to_dict as xml_to_dict
from ._session import SessionMixin as SessionMixin

_T = TypeVar("_T")

@dataclass
class SmartschoolXML(ABC, SessionMixin, metaclass=abc.ABCMeta):
    cache: dict = ...

    def __iter__(self) -> Iterator[_T]: ...
    def get(self) -> _T: ...

@dataclass
class SmartschoolXmlWeeklyCache(SmartschoolXML, ABC, metaclass=abc.ABCMeta):
    timestamp_to_use: datetime | date | None = None

@dataclass
class SmartschoolXmlNoCache(SmartschoolXML, ABC, metaclass=abc.ABCMeta): ...
