# Generated by dev/generate_stubs.py from src/: edit the source and run ./restub instead.
import abc
from abc import ABC
from collections.abc import Iterator
from dataclasses import dataclass
from datetime import date, datetime
from typing import Generic, TypeVar

from _typeshed import DataclassInstance

from ._common import xml_to_dict as xml_to_dict
from ._session import SessionMixin as SessionMixin

_ItemT_co = TypeVar("_ItemT_co", bound="DataclassInstance", covariant=True)

@dataclass
class SmartschoolXML(ABC, SessionMixin, Generic[_ItemT_co], metaclass=abc.ABCMeta):
    cache: dict = ...

    def __iter__(self) -> Iterator[_ItemT_co]: ...
    def get(self) -> _ItemT_co: ...

@dataclass
class SmartschoolXmlWeeklyCache(SmartschoolXML[_ItemT_co], ABC, metaclass=abc.ABCMeta):
    timestamp_to_use: datetime | date | None = None

@dataclass
class SmartschoolXmlNoCache(SmartschoolXML[_ItemT_co], ABC, metaclass=abc.ABCMeta): ...
