#!/usr/bin/env python
from logprise import logger

from smartschool import PathCredentials, Smartschool, TopNavCourses

session = Smartschool(PathCredentials())

for course in TopNavCourses(session):
    logger.info("%s (teacher: %s, url: %s)", course.name, course.teacher, course.url)
