#!/usr/bin/env python
from logprise import logger

from smartschool import Intradesk, IntradeskFile, IntradeskFolder, PathCredentials, Smartschool

session = Smartschool(PathCredentials())


def print_items(folder, indent=0):
    for item in folder:
        prefix = "  " * indent
        if isinstance(item, IntradeskFolder):
            logger.info(f"{prefix}[folder] {item.name}")
            print_items(item, indent + 1)
        elif isinstance(item, IntradeskFile):
            logger.info(f"{prefix}[file]   {item.name}")


intradesk = Intradesk(session=session)
print_items(intradesk)
