#!/usr/bin/env python
from logprise import logger

from smartschool import PathCredentials, Smartschool, TopNavCourses

session = Smartschool(PathCredentials())

for course in TopNavCourses(session):
    logger.info(f"{course.name} (teacher: {course.teacher}, url: {course.url})")
